"""
Django settings for eve_waitlist project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path
import os # Make sure os is imported
from dotenv import load_dotenv # Import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Load .env file ---
# Load environment variables from .env file in BASE_DIR
# This file should be in /Waitlist_Dev/.env
load_dotenv(BASE_DIR / '.env')
# --- End .env file ---


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from .env
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Load from .env, default to False if not set
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ESI / SSO Library
    'esi',
    # Our custom apps
    'esi_auth',
    'waitlist',
    'fleet_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eve_waitlist.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Add the root 'templates' directory
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eve_waitlist.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Load from .env

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME'),        # The name you created in HeidiSQL
        'USER': os.environ.get('DB_USER'),           # Your MySQL username
        'PASSWORD': os.environ.get('DB_PASSWORD'),   # Your MySQL password
        'HOST': os.environ.get('DB_HOST'),         # Or 'localhost'
        'PORT': os.environ.get('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- THE FIX ---
# The AUTHENTICATION_BACKENDS section has been removed
# as it was causing a ModuleNotFoundError.
# We are now logging the user in manually in our view.
# --- END FIX ---


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I1N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Add the root 'static' directory
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- ESI / SSO SETTINGS ---

# This is the contact email required by CCP
ESI_USER_CONTACT_EMAIL = os.environ.get('ESI_USER_CONTACT_EMAIL')

# Set your callback URL in the EVE dev portal to:
# http://127.0.0.1:8000/auth/callback/
#
# Load from .env
ESI_SSO_CLIENT_ID = os.environ.get('ESI_SSO_CLIENT_ID')
ESI_SSO_CLIENT_SECRET = os.environ.get('ESI_SSO_CLIENT_SECRET')

# This MUST point to our /auth/callback/ path
ESI_SSO_CALLBACK_URL = 'http://127.0.0.1:8000/auth/callback/'

LOGIN_REDIRECT_URL = '/'  # Redirect to homepage after login
LOGOUT_REDIRECT_URL = '/'


# This tells Django what the login URL is.
# We point it to the 'login' view inside our 'esi_auth' app.
LOGIN_URL = 'esi_auth:login'


# --- THE FIX: Create multiple scope lists ---

# This tells django-esi what scopes to ask for on login.
# We will define two different sets of scopes.
ESI_SSO_SCOPES_REGULAR = [
    'esi-skills.read_skills.v1',
    'esi-clones.read_implants.v1',
]

ESI_SSO_SCOPES_FC = [
    'esi-skills.read_skills.v1',
    'esi-clones.read_implants.v1',
    'esi-fleets.read_fleet.v1',
    'esi-fleets.write_fleet.v1',
]

# We are removing the old, single ESI_SSO_SCOPES variable.
# Our esi_login view will now choose one of the two lists above.

# --- END FIX ---


# This setting tells Django which domain to use for session cookies.
# We set it to 127.0.0.1 to prevent the "two-domain" bug