# Generated by Django 5.0 on 2025-11-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0006_evetype_hi_slots_evetype_low_slots_evetype_med_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evetype',
            name='attributes_json',
            field=models.TextField(blank=True, help_text='Raw JSON of dogma_attributes from ESI', null=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='meta_level',
            field=models.IntegerField(blank=True, default=0, help_text='Item meta level (Dogma Attr 633)', null=True),
        ),
    ]
