# Generated by Django 5.0 on 2025-11-10 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0007_evetype_attributes_json_evetype_meta_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('icon_id', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='evegroup',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='evetype',
            name='attributes_json',
        ),
        migrations.RemoveField(
            model_name='evetype',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='evetype',
            name='slot',
        ),
        migrations.AddField(
            model_name='evegroup',
            name='icon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evegroup',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='icon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evetype',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evegroup',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='evetype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='pilot.evegroup'),
        ),
        migrations.AlterField(
            model_name='evetype',
            name='hi_slots',
            field=models.IntegerField(blank=True, help_text='Ship: High slots (Dogma Attr 14)', null=True),
        ),
        migrations.AlterField(
            model_name='evetype',
            name='low_slots',
            field=models.IntegerField(blank=True, help_text='Ship: Low slots (Dogma Attr 12)', null=True),
        ),
        migrations.AlterField(
            model_name='evetype',
            name='med_slots',
            field=models.IntegerField(blank=True, help_text='Ship: Medium slots (Dogma Attr 13)', null=True),
        ),
        migrations.AlterField(
            model_name='evetype',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='evetype',
            name='rig_slots',
            field=models.IntegerField(blank=True, help_text='Ship: Rig slots (Dogma Attr 1137)', null=True),
        ),
        migrations.AlterField(
            model_name='evetype',
            name='subsystem_slots',
            field=models.IntegerField(blank=True, help_text='Ship: Subsystem slots (Dogma Attr 1367)', null=True),
        ),
        migrations.AddField(
            model_name='evegroup',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pilot.evecategory'),
        ),
    ]
