# Generated by Django 5.0 on 2025-11-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0008_evecategory_remove_evegroup_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evetype',
            name='slot',
            field=models.IntegerField(blank=True, help_text='Implant slot (if applicable) (Dogma Attr 300)', null=True),
        ),
    ]
