# Generated by Django 5.0 on 2025-11-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0009_evetype_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='evegroup',
            name='ignore_for_rules',
            field=models.BooleanField(db_index=True, default=False, help_text="If True, this group will not appear in the 'Rule Helper' page."),
        ),
    ]
