# Generated by Django 5.0 on 2025-11-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0010_evegroup_ignore_for_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotsnapshot',
            name='implants_cache_expires',
            field=models.DateTimeField(blank=True, help_text='Expiry time of ESI /implants/ endpoint', null=True),
        ),
        migrations.AddField(
            model_name='pilotsnapshot',
            name='public_data_cache_expires',
            field=models.DateTimeField(blank=True, help_text='Expiry time of ESI /character/ public data', null=True),
        ),
        migrations.AddField(
            model_name='pilotsnapshot',
            name='skills_cache_expires',
            field=models.DateTimeField(blank=True, help_text='Expiry time of ESI /skills/ endpoint', null=True),
        ),
    ]
