# Generated by Django 5.0 on 2025-11-06 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EveCharacter',
            fields=[
                ('character_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('character_name', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eve_characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esi_fleet_id', models.BigIntegerField(help_text='The ESI ID of the active fleet.', unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fleet_commander', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commanded_fleets', to='waitlist.evecharacter')),
            ],
        ),
        migrations.CreateModel(
            name='ShipFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_fit', models.TextField(help_text='The ship fit in EFT (or similar) format.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('IN_FLEET', 'In Fleet')], db_index=True, default='PENDING', max_length=10)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_fits', to='waitlist.evecharacter')),
            ],
        ),
        migrations.CreateModel(
            name='FleetWaitlist',
            fields=[
                ('fleet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='waitlist.fleet')),
                ('is_open', models.BooleanField(default=True)),
                ('approved_fits', models.ManyToManyField(blank=True, related_name='waitlists', to='waitlist.shipfit')),
            ],
        ),
    ]
