# Generated by Django 5.0 on 2025-11-06 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0004_shipfit_category_alter_fleetwaitlist_fleet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='esi_fleet_id',
            field=models.BigIntegerField(blank=True, help_text='The ESI ID of the active fleet.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='fleet_commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_fleets', to='waitlist.evecharacter'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fleetwaitlist',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
