# Generated by Django 5.0 on 2025-11-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0007_alter_doctrinefit_fit_items_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinefit',
            name='category',
            field=models.CharField(choices=[('NONE', 'None'), ('DPS', 'DPS'), ('LOGI', 'Logi'), ('SNIPER', 'Sniper'), ('MAR_DPS', 'MAR DPS'), ('MAR_SNIPER', 'MAR Sniper'), ('OTHER', 'Other')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipfit',
            name='category',
            field=models.CharField(choices=[('NONE', 'None'), ('DPS', 'DPS'), ('LOGI', 'Logi'), ('SNIPER', 'Sniper'), ('MAR_DPS', 'MAR DPS'), ('MAR_SNIPER', 'MAR Sniper'), ('OTHER', 'Other')], db_index=True, default='NONE', max_length=20),
        ),
    ]
