# Generated by Django 5.0 on 2025-11-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0008_alter_doctrinefit_category_alter_shipfit_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetWing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wings', to='waitlist.fleet')),
            ],
            options={
                'unique_together': {('fleet', 'wing_id')},
            },
        ),
        migrations.CreateModel(
            name='FleetSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('assigned_category', models.CharField(blank=True, choices=[('NONE', 'None'), ('DPS', 'DPS'), ('LOGI', 'Logi'), ('SNIPER', 'Sniper'), ('MAR_DPS', 'MAR DPS'), ('MAR_SNIPER', 'MAR Sniper'), ('OTHER', 'Other')], db_index=True, max_length=20, null=True, unique=True)),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='waitlist.fleetwing')),
            ],
            options={
                'unique_together': {('wing', 'squad_id')},
            },
        ),
    ]
