# Generated by Django 5.0 on 2025-11-10 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0007_evetype_attributes_json_evetype_meta_level'),
        ('waitlist', '0010_doctrinefit_parsed_fit_json_doctrinefit_raw_fit_eft'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveDogmaAttribute',
            fields=[
                ('attribute_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_id', models.IntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemComparisonRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_is_better', models.BooleanField(default=True, help_text="Check if 'Higher is Better' (e.g., for damage). Uncheck if 'Lower is Better' (e.g., for 'cpuPenalty').")),
                ('attribute', models.ForeignKey(help_text="The attribute to check (e.g., 'shieldCapacity').", on_delete=django.db.models.deletion.CASCADE, to='waitlist.evedogmaattribute')),
                ('group', models.ForeignKey(help_text="The Item Group this rule applies to (e.g., 'Large Shield Extender').", on_delete=django.db.models.deletion.CASCADE, related_name='comparison_rules', to='pilot.evegroup')),
            ],
            options={
                'unique_together': {('group', 'attribute')},
            },
        ),
    ]
