# Generated by Django 5.0 on 2025-11-10 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0008_evecategory_remove_evegroup_category_id_and_more'),
        ('waitlist', '0011_evedogmaattribute_itemcomparisonrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveTypeDogmaAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_values', to='waitlist.evedogmaattribute')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogma_attributes', to='pilot.evetype')),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='waitlist_ev_type_id_33885d_idx')],
                'unique_together': {('type', 'attribute')},
            },
        ),
    ]
