# Generated by Django 5.0 on 2025-11-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0012_evetypedogmaattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharacter',
            name='is_main',
            field=models.BooleanField(default=False, help_text="Is this the user's main character?"),
        ),
    ]
