# Generated by Django 5.0 on 2025-11-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0013_evecharacter_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='evecharacter',
            name='alliance_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='alliance_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='corporation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evecharacter',
            name='corporation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Is this the main character for this user account?'),
        ),
    ]
