# Generated by Django 5.0 on 2025-11-12 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0010_evegroup_ignore_for_rules'),
        ('waitlist', '0014_evecharacter_alliance_id_evecharacter_alliance_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcomparisonrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemcomparisonrule',
            name='ship_type',
            field=models.ForeignKey(blank=True, help_text='If set, this rule *only* applies to this specific ship hull.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_comparison_rules', to='pilot.evetype'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcomparisonrule',
            unique_together={('group', 'attribute', 'ship_type')},
        ),
    ]
