# Generated by Django 5.0 on 2025-11-16 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0015_alter_itemcomparisonrule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinefit',
            name='fit_tier',
            field=models.CharField(blank=True, choices=[('STARTER', 'Starter'), ('INTERMEDIATE', 'Intermediate'), ('OPTIMAL', 'Optimal')], db_index=True, help_text='The quality tier of the fit (e.g., Starter, Optimal).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctrinefit',
            name='fleet_type',
            field=models.ForeignKey(blank=True, help_text='The fleet type this fit is intended for (e.g., Headquarters, Assaults).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='waitlist.fleet'),
        ),
        migrations.AddField(
            model_name='doctrinefit',
            name='hull_tier',
            field=models.CharField(blank=True, choices=[('ENTRY', 'Entry'), ('INTERMEDIATE', 'Intermediate'), ('OPTIMAL', 'Optimal')], db_index=True, help_text='The tier of the hull itself (e.g., Entry, Optimal).', max_length=20, null=True),
        ),
    ]
