# Generated by Django 5.0 on 2025-11-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0016_doctrinefit_fit_tier_doctrinefit_fleet_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinefit',
            name='fit_tier',
            field=models.CharField(blank=True, choices=[('1_STARTER', 'Starter'), ('2_INTERMEDIATE', 'Intermediate'), ('3_OPTIMAL', 'Optimal')], db_index=True, help_text='The quality tier of the fit (e.g., Starter, Optimal).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctrinefit',
            name='hull_tier',
            field=models.CharField(blank=True, choices=[('1_ENTRY', 'Entry'), ('2_INTERMEDIATE', 'Intermediate'), ('3_OPTIMAL', 'Optimal')], db_index=True, help_text='The tier of the hull itself (e.g., Entry, Optimal).', max_length=20, null=True),
        ),
    ]
