# Generated by Django 5.0 on 2025-11-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0017_alter_doctrinefit_fit_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinefit',
            name='tank_type',
            field=models.CharField(blank=True, choices=[('SHIELD', 'Shield'), ('ARMOR', 'Armor')], db_index=True, help_text='The primary tank type of the fit (e.g., Shield, Armor).', max_length=20, null=True),
        ),
    ]
