# Generated by Django 5.0 on 2025-11-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0018_doctrinefit_tank_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinefit',
            name='name',
            field=models.CharField(help_text="e.g., 'Standard Vargur', 'Logi Basilisk'", max_length=255),
        ),
        migrations.AlterField(
            model_name='doctrinefit',
            name='raw_fit_eft',
            field=models.TextField(blank=True, help_text='The raw EFT-formatted fit string.', null=True, unique=True),
        ),
    ]
